services:
  - type: web
    name: vocflight
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: OPENROUTER_API_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: PORT
        value: 5000
